### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by nanof** [ByronMayne/AssetPathAttribute#2]
Nice work! Would it be possible to support Lists of objects, for example:

public List<string> m_PlayerPrefab;

**Comment by ByronMayne** [comment]
Hey Nanof,

`AssetPathAttribute` does currently support generic list. The following does work
```csharp
    [AssetPath.Attribute(typeof(GameObject))]
    public List<string> m_Players;
```
Cheers,
Byron

**Comment by nanof** [comment]
Hi Byron,

that's what I tried but it seems it's not working for me, when I declare the List I get in the inspector "Attribute invalid for type List 1" and it's not possible to drag and drop any prefab.

![captura](https://user-images.githubusercontent.com/3865182/43689980-bdbcd2d2-9902-11e8-8b93-126bbdcd5a8d.PNG)

Cheers
Nanof

**Comment by ByronMayne** [comment]
Hey Nanof,

Asset Path Attribute is just a fancy inspector for string fields. You are seeing that because your code most likely looks like the following.

```csharp
[AssetPath(typeof(Object)]
public List<GameObject> m_Players;
```
You need to make sure it's the following
```csharp
[AssetPath(typeof(Object)]
public List<string> m_Players; 
```
If you have a list of GameObjects there is no point of using AssetPathAttribute because you are using a hard reference.

**Comment by nanof** [comment]
I have this

`   [AssetPath.Attribute(typeof(Object))]
    public List<string> myList; `

and really it's not working :( 
I'm in Unity 2018.1

**Comment by ByronMayne** [comment]
Hmmm,

It looks like in 2018.1 `property.propertyType != SerializedPropertyType.String` is false for `List<string>`. which is weird. Any who I will try to take a look when I get home.

**Comment by ByronMayne** [comment]
It should not be a big deal to fix but I will have to install 2018.1.

**Comment by nanof** [comment]
Ah, that should explain the weird behavior, thanks Byron!

**Comment by ByronMayne** [comment]
No problem!

**Comment by ByronMayne** [comment]
Hey Nanof,
What is the exact version you are using? In `2018.1.0f2` it works fine with the code copied pasted.

Thanks,
Byron

**Comment by nanof** [comment]
Ok I've discovered that the problem is related to having Odin Inspector plugin installed in the project, it seems that its serialization system is colliding with AssetPath, don´t know if is something that could be "fixed" or they are just incompatible

**Comment by ByronMayne** [comment]
Yeah I avoid using Odin myself. 
Could you tell me what `property.propertyType` evaluates too in your code?

**Comment by nanof** [comment]
It's "Generic", I post the complete content of a property

![captura de pantalla 1](https://user-images.githubusercontent.com/3865182/43792181-3f44f2a0-9a78-11e8-9869-c6e9ef38d462.png)

**Comment by ByronMayne** [comment]
Hey,

Could you change the line 
`if (property.propertyType != SerializedPropertyType.String)`
to
`    if (property.propertyType != SerializedPropertyType.String || (property.isArray && property.arrayElementType == "string"))`

From there if that works it's not a big deal to create a workaround. However if the drawer is not functionally that is a bigger issue.

**Comment by nanof** [comment]
Unfortunately it's not working :(
